on:
  workflow_call:
    inputs:
      version:      
        required: true
        type: string

    secrets:
      DOCKERHUB_TOKEN:
        required: true        

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "${{ vars.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3          

      - name: Setup git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: build binaries
        run: |
          CGO=0 GOOS=linux GOARCH=amd64 go build -o kubernetes-ingress-dns-linux-amd64 .
          CGO=0 GOOS=linux GOARCH=arm64 go build -o kubernetes-ingress-dns-linux-arm64 .
      
      - name: prepare release
        run: |
          mkdir -p release
          # generate releases
          for f in ./kubernetes-ingress-dns-*; do
            tar -czf $f.tar.gz $f
          done
          # generate checksums
          cd release
          for f in ./kubernetes-ingress-dns-*; do
            sha256sum $f.tar.gz > $f.tar.gz.sha256
          done


      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          name: "v${{ inputs.version }}"
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "${{ inputs.version }}"
          artifacts: "release/*"

      - name: Set chart version
        run: |
          sed -i 's/0\.0\.0/${{ inputs.version }}/g' charts/kubernetes-ingress-dns/Chart.yaml

      - name: Release chart
        uses: helm/chart-releaser-action@v1.7.0
        with:
          mark_as_latest: false
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: "linux/amd64,linux/arm64"
          tags: "${{ vars.DOCKERHUB_USERNAME }}/kubernetes-ingress-dns:${{ inputs.version }}"
