on:
  workflow_call:
    inputs:
      version:      
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "${{ vars.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: "${{ vars.DOCKERHUB_USERNAME }}/kubernetes-ingress-dns:${{ inputs.version }}"

      - name: Setup git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set chart version
        run: |
          sed -i 's/0\.0\.0/${{ inputs.version }}/g' charts/kubernetes-ingress-dns/Chart.yaml

      - name: Release chart
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          name: "${{ inputs.version }}"
          token: "${{ secrets.GITHUB_TOKEN }}"
