name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Calculate next version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          noNewCommitBehavior: "current"
          noVersionBumpBehavior: "current"
          fallbackTag: "1.0.0"

      - name: Build release (if needed)
        if: ${{ steps.check.outputs.should_build == 'true' }}          
        uses: ./.github/workflows/build.yml
        with:
          version: ${{ steps.semver.outputs.nextStrict }}
