name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      build: ${{ steps.build.outputs.build }}
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Calculate next version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          noNewCommitBehavior: "current"
          noVersionBumpBehavior: "current"
          fallbackTag: "1.0.0"
      
      - name: Set version
        id: version
        run: |
          echo "version=${{ steps.semver.outputs.nextStrict }}" >> "$GITHUB_OUTPUT"

      - name: Set build
        id: build
        run: |
          if [ "${{ steps.semver.outputs.current }}" = "${{ steps.semver.outputs.nextStrict }}" ]; then
            echo "build=false" >> "$GITHUB_OUTPUT"
          else
            echo "build=true" >> "$GITHUB_OUTPUT"
          fi

  build:
    needs: release
    if: needs.release.outputs.build == 'true'
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ needs.release.outputs.version }}
